name: unit tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@master

      - name: Run unit test and generate coverage report
        run: |
          yarn
          yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
